name: Buck2

on:
  push:
  workflow_dispatch:
  schedule: [cron: "40 1,13 * * *"]

permissions:
  contents: read

jobs:
  buck2:
    name: Buck2 on ${{matrix.os == 'ubuntu' && 'Linux' || matrix.os == 'macos' && 'macOS' || matrix.os == 'windows' && 'Windows' || '???'}}
    runs-on: ${{matrix.os}}-latest
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu, macos, windows]
    timeout-minutes: 45
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@1.87.0
        # FIXME: use @stable after prelude supports `--test-runtool`
        # https://github.com/rust-lang/rust/pull/137096
        with:
          components: rust-src
      - uses: dtolnay/install-buck2@latest
      - run: buck2 run demo
      - run: buck2 build ...
      - run: buck2 test ...
