#
# Publish Releases
#
# This workflow can be manually triggered and will then publish the
# specified release to the configured release channels.
#

name: "Publish Releases"

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Git-Tag to Publish"
        default: ""
        required: true
      verify:
        description: "Verify package before publishing"
        default: "yes"
        required: false

concurrency:
  cancel-in-progress: false
  group: "publish"

defaults:
  run:
    shell: "bash"

jobs:
  publish:
    name: "Publish Crate"
    runs-on: "ubuntu-latest"

    env:
      CTX_GITHUB_EVENT_INPUTS_TAG: ${{ github.event.inputs.tag }}
      CTX_GITHUB_EVENT_INPUTS_VERIFY: ${{ github.event.inputs.verify }}
      CTX_GITHUB_REPOSITORY: ${{ github.repository }}

    steps:
    - name: "Verify Input"
      run: |
        if [[ -z "${CTX_GITHUB_EVENT_INPUTS_TAG}" ]] ; then
          echo "error: empty git-tag specified as input"
          exit 1
        fi

    - name: "Clone Repository"
      uses: actions/checkout@v3
      with:
        ref: ${{ github.event.inputs.tag }}

    - name: "Publish Crate"
      env:
        CTX_SECRETS_DEPLOY_CRATESIO_TOKEN: ${{ secrets.DEPLOY_CRATESIO_TOKEN }}
      run: |
        if [[ "${CTX_GITHUB_EVENT_INPUTS_VERIFY}" = "no" ]] ; then
          cargo publish --no-verify --token "${CTX_SECRETS_DEPLOY_CRATESIO_TOKEN}"
        else
          cargo publish --token "${CTX_SECRETS_DEPLOY_CRATESIO_TOKEN}"
        fi

    - name: "Publish GitHub"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        make \
          publish-github \
          "PUBLISH_REPO=${CTX_GITHUB_REPOSITORY}" \
          "PUBLISH_VERSION=${CTX_GITHUB_EVENT_INPUTS_TAG#v}"
