/*
 * Lance Namespace Specification
 *
 * This OpenAPI specification is a part of the Lance namespace specification. It contains 2 parts:  The `components/schemas`, `components/responses`, `components/examples`, `tags` sections define the request and response shape for each operation in a Lance Namespace across all implementations. See https://lance.org/format/namespace/operations for more details.  The `servers`, `security`, `paths`, `components/parameters` sections are for the  Lance REST Namespace implementation, which defines a complete REST server that can work with Lance datasets. See https://lance.org/format/namespace/rest for more details. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AlterColumnsEntry {
    /// Column path to alter
    #[serde(rename = "path")]
    pub path: String,
    /// New data type for the column using JSON representation (optional)
    #[serde(rename = "data_type")]
    pub data_type: serde_json::Value,
    /// New name for the column (optional)
    #[serde(rename = "rename", skip_serializing_if = "Option::is_none")]
    pub rename: Option<String>,
    /// Whether the column should be nullable (optional)
    #[serde(rename = "nullable", skip_serializing_if = "Option::is_none")]
    pub nullable: Option<bool>,
    /// Virtual column alterations (optional)
    #[serde(rename = "virtual_column", skip_serializing_if = "Option::is_none")]
    pub virtual_column: Option<Box<models::AlterVirtualColumnEntry>>,
}

impl AlterColumnsEntry {
    pub fn new(path: String, data_type: serde_json::Value) -> AlterColumnsEntry {
        AlterColumnsEntry {
            path,
            data_type,
            rename: None,
            nullable: None,
            virtual_column: None,
        }
    }
}

