/*
 * Lance Namespace Specification
 *
 * This OpenAPI specification is a part of the Lance namespace specification. It contains 2 parts:  The `components/schemas`, `components/responses`, `components/examples`, `tags` sections define the request and response shape for each operation in a Lance Namespace across all implementations. See https://lance.org/format/namespace/operations for more details.  The `servers`, `security`, `paths`, `components/parameters` sections are for the  Lance REST Namespace implementation, which defines a complete REST server that can work with Lance datasets. See https://lance.org/format/namespace/rest for more details. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// BoostQuery : Boost query that scores documents matching positive query higher and negative query lower
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BoostQuery {
    #[serde(rename = "positive")]
    pub positive: Box<models::FtsQuery>,
    #[serde(rename = "negative")]
    pub negative: Box<models::FtsQuery>,
    /// Boost factor for negative query (default: 0.5)
    #[serde(rename = "negative_boost", skip_serializing_if = "Option::is_none")]
    pub negative_boost: Option<f32>,
}

impl BoostQuery {
    /// Boost query that scores documents matching positive query higher and negative query lower
    pub fn new(positive: models::FtsQuery, negative: models::FtsQuery) -> BoostQuery {
        BoostQuery {
            positive: Box::new(positive),
            negative: Box::new(negative),
            negative_boost: None,
        }
    }
}

