/*
 * Lance Namespace Specification
 *
 * This OpenAPI specification is a part of the Lance namespace specification. It contains 2 parts:  The `components/schemas`, `components/responses`, `components/examples`, `tags` sections define the request and response shape for each operation in a Lance Namespace across all implementations. See https://lance.org/format/namespace/operations for more details.  The `servers`, `security`, `paths`, `components/parameters` sections are for the  Lance REST Namespace implementation, which defines a complete REST server that can work with Lance datasets. See https://lance.org/format/namespace/rest for more details. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// DeleteFromTableRequest : Delete data from table based on a SQL predicate. Returns the number of rows that were deleted. 
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DeleteFromTableRequest {
    #[serde(rename = "identity", skip_serializing_if = "Option::is_none")]
    pub identity: Option<Box<models::Identity>>,
    /// Arbitrary context for a request as key-value pairs. How to use the context is custom to the specific implementation.  REST NAMESPACE ONLY Context entries are passed via HTTP headers using the naming convention `x-lance-ctx-<key>: <value>`. For example, a context entry `{\"trace_id\": \"abc123\"}` would be sent as the header `x-lance-ctx-trace_id: abc123`. 
    #[serde(rename = "context", skip_serializing_if = "Option::is_none")]
    pub context: Option<std::collections::HashMap<String, String>>,
    /// The namespace identifier
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<Vec<String>>,
    /// SQL predicate to filter rows for deletion
    #[serde(rename = "predicate")]
    pub predicate: String,
}

impl DeleteFromTableRequest {
    /// Delete data from table based on a SQL predicate. Returns the number of rows that were deleted. 
    pub fn new(predicate: String) -> DeleteFromTableRequest {
        DeleteFromTableRequest {
            identity: None,
            context: None,
            id: None,
            predicate,
        }
    }
}

