/*
 * Lance Namespace Specification
 *
 * This OpenAPI specification is a part of the Lance namespace specification. It contains 2 parts:  The `components/schemas`, `components/responses`, `components/examples`, `tags` sections define the request and response shape for each operation in a Lance Namespace across all implementations. See https://lance.org/format/namespace/operations for more details.  The `servers`, `security`, `paths`, `components/parameters` sections are for the  Lance REST Namespace implementation, which defines a complete REST server that can work with Lance datasets. See https://lance.org/format/namespace/rest for more details. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DescribeTableIndexStatsResponse {
    /// Distance type for vector indexes
    #[serde(rename = "distance_type", skip_serializing_if = "Option::is_none")]
    pub distance_type: Option<String>,
    /// Type of the index
    #[serde(rename = "index_type", skip_serializing_if = "Option::is_none")]
    pub index_type: Option<String>,
    /// Number of indexed rows
    #[serde(rename = "num_indexed_rows", skip_serializing_if = "Option::is_none")]
    pub num_indexed_rows: Option<i64>,
    /// Number of unindexed rows
    #[serde(rename = "num_unindexed_rows", skip_serializing_if = "Option::is_none")]
    pub num_unindexed_rows: Option<i64>,
    /// Number of indices
    #[serde(rename = "num_indices", skip_serializing_if = "Option::is_none")]
    pub num_indices: Option<i32>,
}

impl DescribeTableIndexStatsResponse {
    pub fn new() -> DescribeTableIndexStatsResponse {
        DescribeTableIndexStatsResponse {
            distance_type: None,
            index_type: None,
            num_indexed_rows: None,
            num_unindexed_rows: None,
            num_indices: None,
        }
    }
}

