/*
 * Lance Namespace Specification
 *
 * This OpenAPI specification is a part of the Lance namespace specification. It contains 2 parts:  The `components/schemas`, `components/responses`, `components/examples`, `tags` sections define the request and response shape for each operation in a Lance Namespace across all implementations. See https://lance.org/format/namespace/operations for more details.  The `servers`, `security`, `paths`, `components/parameters` sections are for the  Lance REST Namespace implementation, which defines a complete REST server that can work with Lance datasets. See https://lance.org/format/namespace/rest for more details. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FragmentStats {
    /// The number of fragments in the table
    #[serde(rename = "num_fragments")]
    pub num_fragments: i64,
    /// The number of uncompacted fragments in the table
    #[serde(rename = "num_small_fragments")]
    pub num_small_fragments: i64,
    /// Statistics on the number of rows in the table fragments
    #[serde(rename = "lengths")]
    pub lengths: Box<models::FragmentSummary>,
}

impl FragmentStats {
    pub fn new(num_fragments: i64, num_small_fragments: i64, lengths: models::FragmentSummary) -> FragmentStats {
        FragmentStats {
            num_fragments,
            num_small_fragments,
            lengths: Box::new(lengths),
        }
    }
}

