/*
 * Lance Namespace Specification
 *
 * This OpenAPI specification is a part of the Lance namespace specification. It contains 2 parts:  The `components/schemas`, `components/responses`, `components/examples`, `tags` sections define the request and response shape for each operation in a Lance Namespace across all implementations. See https://lance.org/format/namespace/operations for more details.  The `servers`, `security`, `paths`, `components/parameters` sections are for the  Lance REST Namespace implementation, which defines a complete REST server that can work with Lance datasets. See https://lance.org/format/namespace/rest for more details. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FragmentSummary {
    #[serde(rename = "min")]
    pub min: i64,
    #[serde(rename = "max")]
    pub max: i64,
    #[serde(rename = "mean")]
    pub mean: i64,
    #[serde(rename = "p25")]
    pub p25: i64,
    #[serde(rename = "p50")]
    pub p50: i64,
    #[serde(rename = "p75")]
    pub p75: i64,
    #[serde(rename = "p99")]
    pub p99: i64,
}

impl FragmentSummary {
    pub fn new(min: i64, max: i64, mean: i64, p25: i64, p50: i64, p75: i64, p99: i64) -> FragmentSummary {
        FragmentSummary {
            min,
            max,
            mean,
            p25,
            p50,
            p75,
            p99,
        }
    }
}

