/*
 * Lance Namespace Specification
 *
 * This OpenAPI specification is a part of the Lance namespace specification. It contains 2 parts:  The `components/schemas`, `components/responses`, `components/examples`, `tags` sections define the request and response shape for each operation in a Lance Namespace across all implementations. See https://lance.org/format/namespace/operations for more details.  The `servers`, `security`, `paths`, `components/parameters` sections are for the  Lance REST Namespace implementation, which defines a complete REST server that can work with Lance datasets. See https://lance.org/format/namespace/rest for more details. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct IndexContent {
    /// Name of the index
    #[serde(rename = "index_name")]
    pub index_name: String,
    /// Unique identifier for the index
    #[serde(rename = "index_uuid")]
    pub index_uuid: String,
    /// Columns covered by this index
    #[serde(rename = "columns")]
    pub columns: Vec<String>,
    /// Current status of the index
    #[serde(rename = "status")]
    pub status: String,
}

impl IndexContent {
    pub fn new(index_name: String, index_uuid: String, columns: Vec<String>, status: String) -> IndexContent {
        IndexContent {
            index_name,
            index_uuid,
            columns,
            status,
        }
    }
}

