/*
 * Lance Namespace Specification
 *
 * This OpenAPI specification is a part of the Lance namespace specification. It contains 2 parts:  The `components/schemas`, `components/responses`, `components/examples`, `tags` sections define the request and response shape for each operation in a Lance Namespace across all implementations. See https://lance.org/format/namespace/operations for more details.  The `servers`, `security`, `paths`, `components/parameters` sections are for the  Lance REST Namespace implementation, which defines a complete REST server that can work with Lance datasets. See https://lance.org/format/namespace/rest for more details. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct NewColumnTransform {
    /// Name of the new column
    #[serde(rename = "name")]
    pub name: String,
    /// SQL expression to compute the column value (optional if virtual_column is specified)
    #[serde(rename = "expression", skip_serializing_if = "Option::is_none")]
    pub expression: Option<String>,
    /// Virtual column definition (optional if expression is specified)
    #[serde(rename = "virtual_column", skip_serializing_if = "Option::is_none")]
    pub virtual_column: Option<Box<models::AddVirtualColumnEntry>>,
}

impl NewColumnTransform {
    pub fn new(name: String) -> NewColumnTransform {
        NewColumnTransform {
            name,
            expression: None,
            virtual_column: None,
        }
    }
}

