/*
 * Lance Namespace Specification
 *
 * This OpenAPI specification is a part of the Lance namespace specification. It contains 2 parts:  The `components/schemas`, `components/responses`, `components/examples`, `tags` sections define the request and response shape for each operation in a Lance Namespace across all implementations. See https://lance.org/format/namespace/operations for more details.  The `servers`, `security`, `paths`, `components/parameters` sections are for the  Lance REST Namespace implementation, which defines a complete REST server that can work with Lance datasets. See https://lance.org/format/namespace/rest for more details. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// QueryTableRequestColumns : Optional columns to return. Provide either column_names or column_aliases, not both. 
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct QueryTableRequestColumns {
    /// List of column names to return
    #[serde(rename = "column_names", skip_serializing_if = "Option::is_none")]
    pub column_names: Option<Vec<String>>,
    /// Object mapping output aliases to source column names
    #[serde(rename = "column_aliases", skip_serializing_if = "Option::is_none")]
    pub column_aliases: Option<std::collections::HashMap<String, String>>,
}

impl QueryTableRequestColumns {
    /// Optional columns to return. Provide either column_names or column_aliases, not both. 
    pub fn new() -> QueryTableRequestColumns {
        QueryTableRequestColumns {
            column_names: None,
            column_aliases: None,
        }
    }
}

