/*
 * Lance Namespace Specification
 *
 * This OpenAPI specification is a part of the Lance namespace specification. It contains 2 parts:  The `components/schemas`, `components/responses`, `components/examples`, `tags` sections define the request and response shape for each operation in a Lance Namespace across all implementations. See https://lance.org/format/namespace/operations for more details.  The `servers`, `security`, `paths`, `components/parameters` sections are for the  Lance REST Namespace implementation, which defines a complete REST server that can work with Lance datasets. See https://lance.org/format/namespace/rest for more details. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// QueryTableRequestFullTextQuery : Optional full-text search query. Provide either string_query or structured_query, not both.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct QueryTableRequestFullTextQuery {
    #[serde(rename = "string_query", skip_serializing_if = "Option::is_none")]
    pub string_query: Option<Box<models::StringFtsQuery>>,
    #[serde(rename = "structured_query", skip_serializing_if = "Option::is_none")]
    pub structured_query: Option<Box<models::StructuredFtsQuery>>,
}

impl QueryTableRequestFullTextQuery {
    /// Optional full-text search query. Provide either string_query or structured_query, not both.
    pub fn new() -> QueryTableRequestFullTextQuery {
        QueryTableRequestFullTextQuery {
            string_query: None,
            structured_query: None,
        }
    }
}

