/*
 * Lance Namespace Specification
 *
 * This OpenAPI specification is a part of the Lance namespace specification. It contains 2 parts:  The `components/schemas`, `components/responses`, `components/examples`, `tags` sections define the request and response shape for each operation in a Lance Namespace across all implementations. See https://lance.org/format/namespace/operations for more details.  The `servers`, `security`, `paths`, `components/parameters` sections are for the  Lance REST Namespace implementation, which defines a complete REST server that can work with Lance datasets. See https://lance.org/format/namespace/rest for more details. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// QueryTableRequestVector : Query vector(s) for similarity search. Provide either single_vector or multi_vector, not both.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct QueryTableRequestVector {
    /// Single query vector
    #[serde(rename = "single_vector", skip_serializing_if = "Option::is_none")]
    pub single_vector: Option<Vec<f32>>,
    /// Multiple query vectors for batch search
    #[serde(rename = "multi_vector", skip_serializing_if = "Option::is_none")]
    pub multi_vector: Option<Vec<Vec<f32>>>,
}

impl QueryTableRequestVector {
    /// Query vector(s) for similarity search. Provide either single_vector or multi_vector, not both.
    pub fn new() -> QueryTableRequestVector {
        QueryTableRequestVector {
            single_vector: None,
            multi_vector: None,
        }
    }
}

