/*
 * Lance Namespace Specification
 *
 * This OpenAPI specification is a part of the Lance namespace specification. It contains 2 parts:  The `components/schemas`, `components/responses`, `components/examples`, `tags` sections define the request and response shape for each operation in a Lance Namespace across all implementations. See https://lance.org/format/namespace/operations for more details.  The `servers`, `security`, `paths`, `components/parameters` sections are for the  Lance REST Namespace implementation, which defines a complete REST server that can work with Lance datasets. See https://lance.org/format/namespace/rest for more details. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TableBasicStats {
    /// Number of deleted rows in the table
    #[serde(rename = "num_deleted_rows")]
    pub num_deleted_rows: i32,
    /// Number of fragments in the table
    #[serde(rename = "num_fragments")]
    pub num_fragments: i32,
}

impl TableBasicStats {
    pub fn new(num_deleted_rows: i32, num_fragments: i32) -> TableBasicStats {
        TableBasicStats {
            num_deleted_rows,
            num_fragments,
        }
    }
}

