/*
 * Lance Namespace Specification
 *
 * This OpenAPI specification is a part of the Lance namespace specification. It contains 2 parts:  The `components/schemas`, `components/responses`, `components/examples`, `tags` sections define the request and response shape for each operation in a Lance Namespace across all implementations. See https://lance.org/format/namespace/operations for more details.  The `servers`, `security`, `paths`, `components/parameters` sections are for the  Lance REST Namespace implementation, which defines a complete REST server that can work with Lance datasets. See https://lance.org/format/namespace/rest for more details. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TableVersion {
    /// Version number
    #[serde(rename = "version")]
    pub version: i64,
    /// Timestamp when the version was created
    #[serde(rename = "timestamp")]
    pub timestamp: String,
    /// Key-value pairs of metadata
    #[serde(rename = "metadata")]
    pub metadata: std::collections::HashMap<String, String>,
}

impl TableVersion {
    pub fn new(version: i64, timestamp: String, metadata: std::collections::HashMap<String, String>) -> TableVersion {
        TableVersion {
            version,
            timestamp,
            metadata,
        }
    }
}

