/*
 * Lance Namespace Specification
 *
 * This OpenAPI specification is a part of the Lance namespace specification. It contains 2 parts:  The `components/schemas`, `components/responses`, `components/examples`, `tags` sections define the request and response shape for each operation in a Lance Namespace across all implementations. See https://lance.org/format/namespace/operations for more details.  The `servers`, `security`, `paths`, `components/parameters` sections are for the  Lance REST Namespace implementation, which defines a complete REST server that can work with Lance datasets. See https://lance.org/format/namespace/rest for more details. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TagContents {
    /// Branch name that the tag was created on (if any)
    #[serde(rename = "branch", skip_serializing_if = "Option::is_none")]
    pub branch: Option<String>,
    /// Version number that the tag points to
    #[serde(rename = "version")]
    pub version: i64,
    /// Size of the manifest file in bytes
    #[serde(rename = "manifestSize")]
    pub manifest_size: i64,
}

impl TagContents {
    pub fn new(version: i64, manifest_size: i64) -> TagContents {
        TagContents {
            branch: None,
            version,
            manifest_size,
        }
    }
}

