name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        # This crate is high-level enough that it probably doesn't matter what OS we test under
        # os: [windows-latest, ubuntu-latest, macos-latest]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3
    - name: Build (no features)
      run: cargo build --verbose --no-default-features
    - name: Build (all features)
      run: cargo build --verbose --all-features
    - name: Run tests
      run: cargo test --verbose --all-features
    # Intentionally not building docs with `--no-default-features` because some links are broken.
    - name: Build documentation
      run: cargo doc --verbose --all-features
