name: Release

# see https://release-plz.ieni.dev/docs/github
# for more information

permissions:
  pull-requests: write
  contents: write
  id-token: write

on:
  push:
    branches:
      - main

jobs:
  release-plz-release:
    name: Release-plz Release
    runs-on: ubuntu-latest
    environment: release
    permissions:
      contents: write # Required for updating the tags etc.
      id-token: write # Required for OIDC token exchange
    if: ${{ github.repository_owner == 'ratatui' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable
      - name: Authenticate with crates.io
        uses: rust-lang/crates-io-auth-action@v1
        id: auth
      - name: Run release-plz
        uses: release-plz/action@v0.5
        with:
          command: release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CARGO_REGISTRY_TOKEN: ${{ steps.auth.outputs.token }}
  release-plz-pr:
    name: Release-plz PR
    runs-on: ubuntu-latest
    permissions:
      contents: write # Required for updating the tags etc.
      pull-requests: write # Required for creating the PR
    if: ${{ github.repository_owner == 'ratatui' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable
      - name: Run release-plz
        uses: release-plz/action@v0.5
        with:
          command: release-pr
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
