dev-version-ext = "dev"

[[pre-release-replacements]]
file = "README.md"
search = "egg = .*"
replace="{{crate_name}} = \"{{version}}\""

[[pre-release-replacements]]
file = "src/tutorials/_02_getting_started.rs"
search = "egg = .*"
replace="{{crate_name}} = \"{{version}}\""

[[pre-release-replacements]]
file = "CHANGELOG.md"
search = "Unreleased"
replace = "{{version}}"

[[pre-release-replacements]]
file = "CHANGELOG.md"
search = "\\.\\.\\.HEAD"
replace = "...{{tag_name}}"
exactly=1

[[pre-release-replacements]]
file = "CHANGELOG.md"
search = "ReleaseDate"
replace = "{{date}}"

[[pre-release-replacements]]
file = "CHANGELOG.md"
search = "<!-- next-header -->"
replace = "<!-- next-header -->\n\n## [Unreleased] - ReleaseDate"
exactly = 1

[[pre-release-replacements]]
file = "CHANGELOG.md"
search = "<!-- next-url -->"
replace = "<!-- next-url -->\n[Unreleased]: https://github.com/mwillsey/egg/compare/{{tag_name}}...HEAD"
exactly = 1
