language: rust
rust:
  - nightly
  - stable
  - 1.12.0

os:
  - linux
  - osx

script:
  - rustc --version | grep nightly && cargo test --features=simd || ( echo skip && rustc --version | grep -v nightly )
  - cargo test --no-default-features
  - cargo test --no-default-features --features=std
  - cargo test --no-default-features --features=std --release
  - rustc --version | grep 1[.][89][.] || rustc --version | grep -v 1[.]2[789][.] | grep 1[.][12][0-9][.]||cargo build --features=validation

